
<?php

$lang = [
    'cs' => [
        'home_hero_title' => 'Osoleno. Tam, kde se kachna stává uměním.',
        'home_hero_button' => 'Rezervovat stůl',
        'home_intro_title' => 'Vítejte v ráji pro milovníky kachny',
        'home_intro_text' => 'V Osoleno věříme, že jeden pokrm, dovedený k absolutní dokonalosti, vydá za tisíc průměrných. Proto jsme svůj um a vášeň zasvětili kachně. Od klasických konfitovaných stehen po odvážné moderní kreace – objevte s námi nekonečné chuťové dimenze, které toto ušlechtilé maso nabízí.',
        'home_menu_preview_title' => 'Ochutnávka z našeho menu',
        'home_menu_preview_button' => 'Detail pokrmu',
        'home_menu_full_button' => 'Zobrazit celé menu',
        'home_experience_title' => 'Zážitek v Osoleno',
        'home_experience_seasonal_title' => 'Sezónní suroviny',
        'home_experience_seasonal_text' => 'Pracujeme s těmi nejlepšími lokálními dodavateli.',
        'home_experience_chef_title' => 'Mistrovství šéfkuchaře',
        'home_experience_chef_text' => 'Každý talíř je umělecké dílo s příběhem.',
        'home_experience_atmosphere_title' => 'Nezapomenutelná atmosféra',
        'home_experience_atmosphere_text' => 'Luxusní a přesto útulné prostředí pro vaše výjimečné chvíle.',
        'home_cta_title' => 'Rezervujte si své místo',
        'home_cta_text' => 'Nenechte si ujít kulinářský zážitek, o kterém se mluví. Rezervujte si stůl ještě dnes.',
        'nav_home' => 'Úvod',
        'nav_about' => 'O nás',
        'nav_menu' => 'Menu',
        'nav_blog' => 'Blog',
        'nav_contact' => 'Kontakt',
        'nav_eshop' => 'E-shop',
        'footer_copyright' => 'Všechna práva vyhrazena.',
        'about_hero_title' => 'Náš příběh',
        'about_story_title' => 'Jsme posedlí detailem',
        'about_story_text' => 'Osoleno nevzniklo přes noc. Zrodilo se z desítek let zkušeností, z cest po světě a z jedné prosté myšlenky: vytvořit v Praze místo, kde bude kachna hlavní hvězdou, nikoli jen položkou v menu. Naším posláním je servírovat nejen jídlo, ale zážitek, na který se nezapomíná.',
        'about_chef_title' => 'Seznamte se se šéfkuchařem',
        'about_chef_name' => 'Martin Novák',
        'about_chef_text' => 'Martinova vášeň pro gastronomii začala již v dětství. Po letech sbírání zkušeností v michelinských restauracích po celé Evropě se rozhodl vrátit domů a otevřít si vlastní podnik, kde by mohl naplno realizovat svou vizi – moderní českou kuchyni zaměřenou na dokonalost v každém detailu.',
        'about_values_title' => 'Naše hodnoty',
        'about_values_freshness_title' => 'Čerstvost',
        'about_values_freshness_text' => 'Suroviny odebíráme od prověřených lokálních farmářů.',
        'about_values_creativity_title' => 'Kreativita',
        'about_values_creativity_text' => 'Nebojíme se experimentovat a posouvat hranice chutí.',
        'about_values_tradition_title' => 'Tradice',
        'about_values_tradition_text' => 'Vycházíme z poctivých receptů, kterým dáváme moderní tvář.',
        'about_values_hospitality_title' => 'Pohostinnost',
        'about_values_hospitality_text' => 'Chceme, abyste se u nás cítili jako doma.',
        'about_gallery_title' => 'Galerie interiéru',
        'menu_hero_title' => 'Naše Menu',
        'menu_intro_title' => 'Sezónní nabídka',
        'menu_intro_text' => 'Naše menu se pravidelně mění podle dostupnosti těch nejčerstvějších sezónních surovin. Níže naleznete aktuální nabídku, kterou pro vás s péčí připravil náš šéfkuchař.',
        'menu_allergens_text' => 'Máte dotaz ohledně alergenů? Neváhejte se obrátit na naši obsluhu, která vám ráda poskytne veškeré potřebné informace.',
        'eshop_hero_title' => 'E-shop',
        'eshop_intro_title' => 'Objednejte si kousek Osoleno domů',
        'eshop_intro_text' => 'Vybrané speciality si nyní můžete vychutnat i v pohodlí vašeho domova. Nabízíme polotovary a dezerty k osobnímu vyzvednutí nebo doručení.',
        'eshop_step1_title' => 'Vyberte si',
        'eshop_step1_text' => 'Prohlédněte si naši nabídku a vložte produkty do košíku.',
        'eshop_step2_title' => 'Vyplňte údaje',
        'eshop_step2_text' => 'Zadejte své kontaktní a doručovací údaje.',
        'eshop_step3_title' => 'Zaplaťte při převzetí',
        'eshop_step3_text' => 'Platba probíhá v hotovosti nebo kartou při osobním odběru či doručení.',
        'eshop_no_products' => 'Momentálně nemáme žádné produkty v nabídce.',
        'eshop_cart_title' => 'Nákupní košík',
        'eshop_cart_empty' => 'Váš košík je prázdný.',
        'eshop_cart_total' => 'Celková cena:',
        'eshop_order_form_title' => 'Objednávkový formulář',
        'eshop_order_login_prompt' => 'Pro dokončení objednávky se prosím <a href="?page=login">přihlaste</a> nebo <a href="?page=register">zaregistrujte</a>.',
        'eshop_account_link_logged_in' => 'Jste přihlášen jako: %s. <a href="?page=account">Můj účet</a> | <a href="?page=logout">Odhlásit se</a>',
        'eshop_account_link_logged_out' => 'Máte u nás účet? <a href="?page=login">Přihlaste se</a> pro zobrazení historie objednávek.',
        'blog_hero_title' => 'Blog',
        'blog_widget_categories_title' => 'Kategorie',
        'blog_widget_chef_word_title' => 'Slovo šéfkuchaře',
        'blog_widget_chef_word_text' => 'Krátké tipy a triky přímo od našeho mistra kuchyně.',
        'blog_widget_newsletter_title' => 'Odběr novinek',
        'blog_widget_newsletter_placeholder' => 'Váš e-mail',
        'blog_widget_newsletter_button' => 'Odebírat',
        'contact_hero_title' => 'Kontakt',
        'contact_info_title' => 'Spojte se s námi',
        'contact_info_address' => 'Adresa',
        'contact_info_phone' => 'Telefon',
        'contact_info_email' => 'E-mail',
        'contact_info_opening_hours' => 'Otevírací doba',
        'contact_info_opening_hours_text' => 'Po - Ne: 11:00 - 23:00',
        'contact_reservation_form_title' => 'Rezervační formulář',
        'contact_form_name' => 'Jméno a příjmení',
        'contact_form_email' => 'E-mail',
        'contact_form_phone' => 'Telefon',
        'contact_form_date' => 'Datum',
        'contact_form_time' => 'Čas',
        'contact_form_guests' => 'Počet osob',
        'contact_form_submit_reservation' => 'Odeslat rezervaci',
        'contact_reservation_success' => 'Rezervace byla úspěšně odeslána!',
        'contact_reservation_error' => 'Chyba při odesílání rezervace:',
        'contact_faq_title' => 'Často kladené otázky',
        'contact_faq_parking_question' => 'Kde mohu zaparkovat?',
        'contact_faq_parking_answer' => 'V okolí restaurace se nachází několik placených parkovacích zón. Doporučujeme využít parkovací dům v blízkosti.',
        'contact_faq_barrier_free_question' => 'Je restaurace bezbariérová?',
        'contact_faq_barrier_free_answer' => 'Ano, naše restaurace je plně bezbariérová.',
        'contact_faq_payment_question' => 'Jaké platební metody přijímáte?',
        'contact_faq_payment_answer' => 'Přijímáme hotovost a všechny běžné platební karty.',
        '404_title' => 'Stránka nenalezena',
        '404_text' => 'Omlouváme se, ale požadovaná stránka neexistuje.',
        '404_button' => 'Zpět na úvodní stránku',
        'register_title' => 'Registrace',
        'register_success' => 'Registrace proběhla úspěšně! Nyní se můžete přihlásit.',
        'register_error' => 'Chyba při registraci:',
        'register_login_prompt' => 'Už máte účet? <a href="?page=login">Přihlaste se zde</a>',
        'login_title' => 'Přihlášení',
        'login_error' => 'Neplatný e-mail nebo heslo.',
        'login_register_prompt' => 'Nemáte účet? <a href="?page=register">Zaregistrujte se zde</a>',
        'account_title' => 'Můj účet',
        'account_user_data_title' => 'Vaše údaje',
        'account_user_name' => 'Jméno:',
        'account_user_email' => 'E-mail:',
        'account_user_phone' => 'Telefon:',
        'account_user_address' => 'Adresa:',
        'account_order_history_title' => 'Historie objednávek',
        'account_order_id' => 'ID objednávky',
        'account_order_total_price' => 'Celková cena',
        'account_order_date' => 'Datum objednávky',
        'account_order_details' => 'Detaily',
        'account_no_orders' => 'Zatím nemáte žádné objednávky.',
        'eshop_add_to_cart_button' => 'Přidat do košíku',
        'eshop_place_order_button' => 'Odeslat objednávku',
        'eshop_order_success' => 'Objednávka byla úspěšně odeslána!',
        'eshop_order_error' => 'Chyba při odesílání objednávky:',
        'menu_no_items' => 'V této kategorii se momentálně nenachází žádné položky.',
    ]
];

function __($key) {
    global $lang;
    $current_lang = 'cs'; // Zde by se určoval aktuální jazyk (např. z URL nebo session)
    return $lang[$current_lang][$key] ?? $key;
}

?>
